name: "OVH deployment"
description: "Deploy a repositories contents to an OVH Hosting Plan with SSH support"
author: gregorybellencontre
branding:
  icon: "truck"
  color: "blue"
runs:
  using: "docker"
  image: "Dockerfile"
